# NOTE: Do not edit, file was generated by jhconvert

Name: gstreamer0.10-espeak
Version: 0.3
Release: %mkrel 1
Summary: Simple gstreamer plugin to use espeak by way of sound source
License: LGPLv2+
Group: Sound
Url: http://sugarlabs.org/go/DevelopmentTeam/gst-plugins-espeak

Source: http://download.sugarlabs.org/sources/honey/gst-plugins-espeak/gst-plugins-espeak-0.3.tar.bz2

Requires: espeak  
Requires: gstreamer0.10-plugins-base  
Requires: gstreamer0.10-plugins-good  
Requires: gstreamer  

BuildRequires: libespeak-devel  
BuildRequires: libgstreamer-plugins-base-devel  
BuildRequires: libgstreamer-devel  

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
Simple gstreamer plugin to use espeak by way of sound source.
It was developed to simplify espeak usage in Sugar Speak activity.

%prep
%setup -q -n gst-plugins-espeak-0.3


# eliminate %%configure's "clever" behaviour
%define __libtoolize true

%build
%configure 
make 

%install
rm -rf %{buildroot}
make  \
	install \
	DESTDIR=%{buildroot}


%clean
rm -rf %{buildroot}

%files 
%defattr(-,root,root,-)
%{_libdir}/gstreamer*/*
%doc AUTHORS COPYING NEWS README

