# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name:		gstreamer0.10-espeak
Version:	0.3.5
Release:	2
Summary:	Simple gstreamer plugin to use espeak by way of sound source
License:	LGPLv2+
Group:		Sound
Url:		https://sugarlabs.org/go/DevelopmentTeam/gst-plugins-espeak
Source:		http://download.sugarlabs.org/sources/honey/gst-plugins-espeak/gst-plugins-espeak-%{version}.tar.gz
Requires:	espeak
Requires:	gstreamer0.10-plugins-base
Requires:	gstreamer0.10-plugins-good
Requires:	gstreamer

BuildRequires:	libespeak-devel
BuildRequires:	pkgconfig(gstreamer-0.10)
BuildRequires:	pkgconfig(gstreamer-plugins-base-0.10)

%description
Simple gstreamer plugin to use espeak by way of sound source.
It was developed to simplify espeak usage in Sugar Speak activity.

%prep
%setup -q -n gst-plugins-espeak-%{version}
sed -i 's/NANO=1/NANO=0/g' configure

%build
%configure2_5x
%make

%install
%__rm -rf %{buildroot}
%makeinstall_std

%clean
%__rm -rf %{buildroot}

%files
%doc AUTHORS COPYING NEWS README
%{_libdir}/gstreamer*/*



%changelog
* Mon May 28 2012 Andrey Bondrov <abondrov@mandriva.org> 0.3.5-1mdv2012.0
+ Revision: 800949
- New version 0.3.5, spec cleanup

* Fri Nov 05 2010 Funda Wang <fwang@mandriva.org> 0.3.3-2mdv2011.0
+ Revision: 593571
- build release plugin
- rebuild for gstreamer provides

* Fri May 01 2009 Aleksey Lim <alsroot@mandriva.org> 0.3.3-1mdv2010.0
+ Revision: 369903
- update version to 0.3.3

* Sat Mar 21 2009 Aleksey Lim <alsroot@mandriva.org> 0.3.1-1mdv2009.1
+ Revision: 360049
- update version to 0.3.1

* Fri Mar 13 2009 Aleksey Lim <alsroot@mandriva.org> 0.3-1mdv2009.1
+ Revision: 354524
- update to 0.3 release
- update to new version 0.2

* Tue Feb 17 2009 Aleksey Lim <alsroot@mandriva.org> 0.1-1mdv2009.1
+ Revision: 341766
- Initial commit

