# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: gstreamer0.10-espeak
Version: 0.3.3
Release: %mkrel 2
Summary: Simple gstreamer plugin to use espeak by way of sound source
License: LGPLv2+
Group: Sound
Url: http://sugarlabs.org/go/DevelopmentTeam/gst-plugins-espeak

Source: http://download.sugarlabs.org/sources/honey/gst-plugins-espeak/gst-plugins-espeak-0.3.3.tar.bz2

Requires: espeak  
Requires: gstreamer0.10-plugins-base  
Requires: gstreamer0.10-plugins-good  
Requires: gstreamer  

BuildRequires: libespeak-devel  
BuildRequires: libgstreamer-plugins-base-devel  
BuildRequires: libgstreamer-devel  

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root


%description
Simple gstreamer plugin to use espeak by way of sound source.
It was developed to simplify espeak usage in Sugar Speak activity.

%prep
%setup -q -n gst-plugins-espeak-0.3.3
sed -i 's/NANO=1/NANO=0/g' configure

%build
%configure2_5x
%make

%install
rm -rf %{buildroot}
%makeinstall_std


%clean
rm -rf %{buildroot}

%files 
%defattr(-,root,root,-)
%{_libdir}/gstreamer*/*
%doc AUTHORS COPYING NEWS README

